-- 코드를 입력하세요
SELECT
    CAR_ID,
    ROUND(SUM(DURATION)/COUNT(*),1) AS AVERAGE_DURATION
FROM
    (
        SELECT
            HISTORY_ID,
            CAR_ID,
            DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    ) AS B
GROUP BY
    CAR_ID
HAVING
    AVERAGE_DURATION >= 7
ORDER BY
    AVERAGE_DURATION DESC, 
    CAR_ID DESC