-- 코드를 입력하세요
WITH t1 AS (
    SELECT
        USER_ID
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = '2021'
), t2 AS (
    SELECT
        COUNT(USER_ID) AS TOTAL
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = '2021'
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT t3.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT t3.USER_ID)/(SELECT TOTAL FROM t2), 1) AS PUCHASED_RATIO
FROM
    t1 JOIN ONLINE_SALE t3
    ON t1.USER_ID = t3.USER_ID
GROUP BY
    YEAR, 
    MONTH
ORDER BY
    YEAR,
    MONTH