-- 코드를 입력하세요
WITH t1 AS (
    SELECT
        CAR_ID,
        CAR_TYPE,
        DAILY_FEE
    FROM
        CAR_RENTAL_COMPANY_CAR
    WHERE
        CAR_TYPE = '트럭'
), t2 AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE)+1 AS DAYS,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN 0
            WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN 7
            WHEN DATEDIFF(END_DATE, START_DATE)+1 < 90 THEN 30
            ELSE 90
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
), t3 AS (
    SELECT
        CAR_TYPE,
        CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) AS DURATION_TYPE,
        CAST(REPLACE(DISCOUNT_RATE, '%', '') AS UNSIGNED) AS DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE
        CAR_TYPE = '트럭'
)

SELECT
    t2.HISTORY_ID,
    CASE
        WHEN DISCOUNT_RATE IS NOT NULL
            THEN FLOOR(DAILY_FEE * 0.01 * (100 - DISCOUNT_RATE) * DAYS)
        ELSE DAILY_FEE * DAYS
    END AS FEE
FROM
    t1 JOIN t2
    ON t1.CAR_ID = t2.CAR_ID
    LEFT OUTER JOIN t3
    ON t2.DURATION_TYPE = t3.DURATION_TYPE
ORDER BY
    FEE DESC,
    HISTORY_ID DESC