-- 코드를 입력하세요
SELECT DISTINCT
    c1.CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR c1
    JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY c2
    ON c1.CAR_ID = c2.CAR_ID
WHERE
    CAR_TYPE = '세단'
    AND
    DATE_FORMAT(START_DATE, '%Y-%m') = '2022-10'
ORDER BY
    CAR_ID DESC