-- 코드를 입력하세요
SELECT 
    INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO i INNER JOIN
    FIRST_HALF j
    ON i.FLAVOR = j.FLAVOR
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER