-- 코드를 입력하세요
SELECT
    PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM
    (
        SELECT
            TRUNCATE(PRICE/10000, 0)*10000 AS PRICE_GROUP
        FROM
            PRODUCT
    ) AS A
GROUP BY
    PRICE_GROUP
ORDER BY
    PRICE_GROUP